/** Config Tailwind IDENTIQUE à celle embarquée dans code.html (Stitch) —
 *  RIEN de remappé cette fois : couleurs Material 3 et police Plus Jakarta
 *  Sans reprises telles quelles, à la demande explicite de l'utilisateur
 *  après plusieurs passes de remap qui n'ont pas convaincu. */
module.exports = {
  important: '.machine-modal-edit',
  content: ['./mockup.html'],
  corePlugins: { preflight: false },
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#89ceff",
        "error": "#ba1a1a",
        "primary-container": "#0ea5e9",
        "surface-container": "#e5eeff",
        "tertiary-fixed-dim": "#ffb786",
        "surface-bright": "#f8f9ff",
        "inverse-surface": "#213145",
        "tertiary-fixed": "#ffdcc6",
        "outline-variant": "#bec8d2",
        "on-secondary-fixed-variant": "#40465b",
        "on-tertiary-container": "#542600",
        "tertiary-container": "#ee7d1a",
        "on-background": "#0b1c30",
        "on-secondary-container": "#5c6278",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001e2f",
        "inverse-primary": "#89ceff",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "outline": "#6e7881",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#006591",
        "on-primary-fixed-variant": "#004c6e",
        "secondary": "#585e74",
        "inverse-on-surface": "#eaf1ff",
        "primary": "#006591",
        "on-surface-variant": "#3e4850",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#723600",
        "primary-fixed": "#c9e6ff",
        "on-primary-container": "#003751",
        "on-surface": "#0b1c30",
        "on-secondary-fixed": "#151b2e",
        "surface-variant": "#d3e4fe",
        "surface-container-high": "#dce9ff",
        "background": "#f8f9ff",
        "surface": "#f8f9ff",
        "secondary-fixed-dim": "#c0c5e0",
        "on-secondary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "on-tertiary-fixed": "#311300",
        "surface-container-highest": "#d3e4fe",
        "on-error-container": "#93000a",
        "surface-dim": "#cbdbf5",
        "secondary-container": "#dadef9",
        "secondary-fixed": "#dce1fc",
        "tertiary": "#964900",
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '1rem',
        'space-sm': '0.5rem',
        'gutter': '1.5rem',
        'gutter-mobile': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'space-xs': '0.25rem',
        'margin': '2rem',
      },
      fontFamily: {
        'display-lg': ['Plus Jakarta Sans'],
        'body-sm': ['Plus Jakarta Sans'],
        'headline-sm': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'display-lg-mobile': ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
        'body-lg': ['Plus Jakarta Sans'],
        'label-md': ['Plus Jakarta Sans'],
        'label-lg': ['Plus Jakarta Sans'],
        'label-sm': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
      },
    },
  },
};
